ifeq ($(OD),debug)
	FLAG=-g -fno-inline -DDEBUG -DBOUNDS_CHECK
endif
ifeq ($(OD),dist)
	FLAG=-O3 -g -DDEBUG
endif
ifeq ($(OD),static)
	FLAG=-O3 -g -DDEBUG
endif
ifeq ($(OD),prof)
	FLAG=-g -pg -O
endif
ifeq ($(OD),opt)
	FLAG=-g -O
endif
ifeq ($(OD),opt2)
	FLAG=-g -O2
endif
ifeq ($(OD),opt3)
	FLAG=-g -O3
endif

BOOST   = /home/qianyuxx/local
B_LIB   = -L$(BOOST)/lib -Wl,-rpath,$(BOOST)/lib
G_LIB   = .